version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file-processor
    ports:
      - "5432:5432"